version: "3"
services:
  node-app:
    build: .
    depends_on:
      - mongo

  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=kalpesh
      - MONGO_INITDB_ROOT_PASSWORD=kalpesh123
    volumes:
      - mongo-db:/data/db
  redis:
    image: redis      

volumes:
  mongo-db:

  