version: "3"
services:
  node-app:
    build:
      context: .
      args:
        NODE_ENV: production
    ports:
      - "9000:3000"
    environment:
      - NODE_ENV=production
    command: node index.js