version: "3"
services:
  node-app:
    build: 
      context: .
      args:
        NODE_ENV: development
    ports:
      - "8000:3000"
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - MONGO_USER=kalpesh
      - MONGO_PASSWORD=kalpesh123
      - SESSION_SECRET=secret
    command: npm run dev
  
  mongo:
    environment:
      - MONGO_INITDB_ROOT_USERNAME=kalpesh
      - MONGO_INITDB_ROOT_PASSWORD=kalpesh123
  
  